### ISSUE TITLE
[Standalone 0.4.2] Crash at tab close

### ISSUE THREAD

**Issue by FlachyJoe** [timothyschoen/PlugData#51]
Hi,
the current linux version segfaults when a tab is closed:
```
Thread 1 "PlugData" received signal SIGSEGV, Segmentation fault.
juce::TabbedComponent::setCurrentTabIndex (this=0x555003f96e3e, newTabIndex=0, sendChangeMessage=true) at /usr/include/c++/11/bits/unique_ptr.h:173
173	      pointer    _M_ptr() const { return std::get<0>(_M_t); }

(gdb) backtrace 
#0  juce::TabbedComponent::setCurrentTabIndex (this=0x555003f96e3e, newTabIndex=0, sendChangeMessage=true) at /usr/include/c++/11/bits/unique_ptr.h:173
#1  0x0000555555a07b5b in operator() (__closure=0x555556a3e970) at /home/users/GIT/PlugData/Source/PluginEditor.cpp:545
#2  std::__invoke_impl<void, PlugDataPluginEditor::addTab(Canvas*, bool)::<lambda()>&> (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#3  std::__invoke_r<void, PlugDataPluginEditor::addTab(Canvas*, bool)::<lambda()>&> (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#4  std::_Function_handler<void(), PlugDataPluginEditor::addTab(Canvas*, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/11/bits/std_function.h:291
#5  0x000055555572be11 in std::function<void ()>::operator()() const (this=0x555556b94c98) at /usr/include/c++/11/bits/std_function.h:560
#6  juce::Button::sendClickMessage (this=0x555556b94bb0, modifiers=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/buttons/juce_Button.cpp:425
#7  0x00005555557671ce in juce::Button::mouseUp (this=0x555556b94bb0, e=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/buttons/juce_Button.cpp:490
#8  0x000055555574cd94 in juce::Component::internalMouseUp (this=<optimized out>, source=..., relativePointerState=..., time=..., oldModifiers=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2565
#9  0x00005555557f06ef in juce::MouseInputSourceInternal::sendMouseUp (oldMods=..., time=..., pointerState=..., comp=..., this=0x55555629b8b0)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:559
#10 juce::MouseInputSourceInternal::setButtons (this=this@entry=0x55555629b8b0, pointerState=..., time=time@entry=..., 
    newButtonState=newButtonState@entry=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:185
#11 0x0000555555777070 in juce::MouseInputSourceInternal::handleEvent (pen=..., pen=..., newOrientation=<optimized out>, newPressure=<optimized out>, 
    newMods=..., time=..., positionWithinPeer=..., newPeer=..., this=<optimized out>)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:312
#12 juce::MouseInputSource::handleEvent (this=this@entry=0x7fffffffd9c0, peer=..., pos=..., pos@entry=..., time=time@entry=1649405943376, mods=..., 
    mods@entry=..., pressure=<optimized out>, orientation=<optimized out>, penDetails=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:609
#13 0x00005555557772a5 in juce::ComponentPeer::handleMouseEvent (this=this@entry=0x5555562b79e0, type=type@entry=juce::MouseInputSource::mouse, pos=..., 
    newMods=..., newPressure=newPressure@entry=0, newOrientation=newOrientation@entry=0, time=1649405943376, pen=..., touchIndex=touchIndex@entry=0)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:87
#14 0x0000555555777787 in juce::XWindowSystem::handleButtonReleaseEvent (this=<optimized out>, peer=<optimized out>, buttonRelEvent=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3531
#15 0x000055555577974d in juce::XWindowSystem::handleWindowMessage (this=0x55555629bae0, peer=<optimized out>, event=...)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3264
#16 0x0000555555779d11 in operator() (__closure=0x55555629b2a0)
    at /home/users/GIT/PlugData/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3188
#17 std::__invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int> (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#18 std::__invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int> (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#19 std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., 
    __args#0=<optimized out>) at /usr/include/c++/11/bits/std_function.h:291
#20 0x00005555558b83a3 in std::function<void (int)>::operator()(int) const (__args#0=<optimized out>, this=0x55555629b2a0)
    at /usr/include/c++/11/bits/std_function.h:560
#21 juce::InternalRunLoop::dispatchPendingEvents (this=this@entry=0x55555629b1f0)
    at /home/user/GIT/PlugData/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:185
#22 0x00005555558b5fdd in juce::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=returnIfNoPendingMessages@entry=false)
    at /home/user/GIT/PlugData/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:299
#23 0x00005555558b6047 in juce::MessageManager::runDispatchLoop (this=0x55555629b180)
   juce_events/messages/juce_MessageManager.cpp:107
#24 0x000055555563af70 in juce::JUCEApplicationBase::main () at /home/user/GIT/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:262
#25 0x00007ffff78b3fd0 in __libc_start_call_main (main=main@entry=0x555555637840 <main(int, char**)>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdfa8) at ../sysdeps/nptl/libc_start_call_main.h:58
#26 0x00007ffff78b407d in __libc_start_main_impl (main=0x555555637840 <main(int, char**)>, argc=1, argv=0x7fffffffdfa8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf98) at ../csu/libc-start.c:409
#27 0x0000555555649e05 in _start ()
```

**Comment by timothyschoen** [comment]
Does this happen every time or occasionally? I wasn't able to reproduce this crash

**Comment by FlachyJoe** [comment]
Every time.
Steps to reproduce:

1. launch PlugData
2. insert a [pd test]
3. RMB/open
4. click the cross of the test tab
5. PlugData crash

**Comment by timothyschoen** [comment]
Still nothing happening here unfortunately. Are you using the release version or are you building from source? I'll try it on my other Linux PC to see if it happens there.

**Comment by timothyschoen** [comment]
On my Arch installation I can reproduce the crash, so I'll figure it out from here. Thanks for reporting!

**Comment by FlachyJoe** [comment]
> Are you using the release version or are you building from source?

I'm building from source. You can increase version number in source after each release so current would show v0.4.3.

**Comment by timothyschoen** [comment]
That's a good idea, I used to bump the version number before the release. 

This is a very strange bug: it only happens on some kinds of Linux. On Ubuntu 20.04, Windows 11 and Mac there's no problem.

**Comment by timothyschoen** [comment]
This is problem with gcc, it doesn't happen when using clang, which explains why it worked on my ubuntu build. Fix coming soon

**Comment by timothyschoen** [comment]
Should be fixed!

**Comment by FlachyJoe** [comment]
It works ! :1st_place_medal:
