### ISSUE TITLE
Segmentation fault on Linux. Build from HEAD 

### ISSUE THREAD

**Issue by KottV** [timothyschoen/PlugData#81]
Hi,

I cannot tell which commit to blame, but it's reproducible with recent 5187d032c1f625e1e43771a2efdebf179a2fdfa1
OS openSUSE TW, gcc 1.2.1

Standalone crashes with that backtrace (not sure if it's useful):
```
Thread 1 "PlugData" received signal SIGSEGV, Segmentation fault.
0x00000000004ba836 in juce::WeakReference<juce::Component, juce::ReferenceCountedObject>::SharedPointer::get (this=0x3) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_core/memory/juce_WeakReference.h:132
132             inline ObjectType* get() const noexcept     { return owner; }
Missing separate debuginfos, use: zypper install libX11-6-debuginfo-1.8-1.1.x86_64
(gdb) bt
#0  0x00000000004ba836 in juce::WeakReference<juce::Component, juce::ReferenceCountedObject>::SharedPointer::get (this=0x3) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_core/memory/juce_WeakReference.h:132
#1  0x00000000004d2e61 in juce::WeakReference<juce::Component, juce::ReferenceCountedObject>::Master::getSharedPointer (this=0x1c6dd08, object=0x1c6dc40) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_core/memory/juce_WeakReference.h:173
#2  0x00000000004c6af9 in juce::WeakReference<juce::Component, juce::ReferenceCountedObject>::getRef (o=0x1c6dc40) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_core/memory/juce_WeakReference.h:207
#3  0x00000000004c4175 in juce::WeakReference<juce::Component, juce::ReferenceCountedObject>::WeakReference (this=0x7fffffffcf20, object=0x1c6dc40) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_core/memory/juce_WeakReference.h:84
#4  0x00000000004f6a25 in juce::Component::BailOutChecker::BailOutChecker (this=0x7fffffffcf20, component=0x1c6dc40) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:3229
#5  0x00000000004f0fa6 in juce::Component::internalHierarchyChanged (this=0x1c6dc40) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:1703
#6  0x00000000004f0892 in juce::Component::addChildComponent (this=0x1c6d7d0, child=..., zOrder=3) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:1527
#7  0x00000000004f091a in juce::Component::addChildComponent (this=0x1c6d7d0, child=0x1c6dc40, zOrder=-1) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:1541
#8  0x00000000009f0734 in Sidebar::Sidebar (this=0x1c6d7d0, instance=0x16665e0) at /home/kv/src/audio/PlugData/Source/Sidebar/Sidebar.cpp:28
#9  0x00000000009c4e7a in PlugDataPluginEditor::PlugDataPluginEditor (this=0x1c6d420, p=...) at /home/kv/src/audio/PlugData/Source/PluginEditor.cpp:18
#10 0x00000000009de143 in PlugDataAudioProcessor::createEditor (this=0x16665e0) at /home/kv/src/audio/PlugData/Source/PluginProcessor.cpp:665
#11 0x0000000000484991 in juce::AudioProcessor::createEditorIfNeeded (this=0x16665e0) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_audio_processors/processors/juce_AudioProcessor.cpp:890
#12 0x000000000043df9b in PlugDataWindow::MainContentComponent::MainContentComponent (this=0x16e2320, filterWindow=...) at /home/kv/src/audio/PlugData/Source/Standalone/PlugDataWindow.h:618
#13 0x000000000043dac0 in PlugDataWindow::PlugDataWindow (this=0x164b1b0, title=..., backgroundColour=..., settingsToUse=0x164aa00, takeOwnershipOfSettings=false, preferredDefaultDeviceName=..., preferredSetupOptions=0x0, constrainToConfiguration=..., autoOpenMidiDevices=false)
    at /home/kv/src/audio/PlugData/Source/Standalone/PlugDataWindow.h:517
#14 0x000000000043fa06 in PlugDataApp::createWindow (this=0x162ee10) at /home/kv/src/audio/PlugData/Source/Standalone/PlugDataApp.cpp:81
#15 0x000000000043fae0 in PlugDataApp::initialise (this=0x162ee10) at /home/kv/src/audio/PlugData/Source/Standalone/PlugDataApp.cpp:88
#16 0x00000000007b877b in juce::JUCEApplicationBase::initialiseApp (this=0x162ee10) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:297
#17 0x0000000000587464 in juce::JUCEApplication::initialiseApp (this=0x162ee10) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/application/juce_Application.cpp:92
#18 0x00000000007b8632 in juce::JUCEApplicationBase::main () at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:256
#19 0x00000000007b856c in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffd748) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:240
#20 0x0000000000437e14 in main (argc=1, argv=0x7fffffffd748) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp:47
```

VST3 in Carla gives the next:
```
Thread 1 "carla-bridge-na" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff754b62b in kill () at ../sysdeps/unix/syscall-template.S:120
120     ../sysdeps/unix/syscall-template.S: Directory not empty.
Missing separate debuginfos, use: zypper install carla-debuginfo-2.4.3+git.0.f22915f6e-56.13.x86_64
(gdb) bt
#0  0x00007ffff754b62b in kill () at ../sysdeps/unix/syscall-template.S:120
#1  0x00007ffff4883c54 in juce::Desktop::setDefaultLookAndFeel(juce::LookAndFeel*) (this=0x555556004170, newDefaultLookAndFeel=0x555555a571e0) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/desktop/juce_Desktop.cpp:108
#2  0x00007ffff48b0877 in juce::LookAndFeel::setDefaultLookAndFeel(juce::LookAndFeel*) (newDefaultLookAndFeel=0x555555a571e0) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_gui_basics/lookandfeel/juce_LookAndFeel.cpp:114
#3  0x00007ffff4753262 in PlugDataAudioProcessor::PlugDataAudioProcessor() (this=0x5555559dd200) at /home/kv/src/audio/PlugData/Source/PluginProcessor.cpp:75
#4  0x00007ffff475873a in createPluginFilter() () at /home/kv/src/audio/PlugData/Source/PluginProcessor.cpp:1016
#5  0x00007ffff46659aa in juce::createPluginFilterOfType(juce::AudioProcessor::WrapperType) (type=juce::AudioProcessor::wrapperType_VST3) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_audio_plugin_client/utility/juce_CreatePluginFilter.h:39
#6  0x00007ffff4670a49 in juce::JuceVST3Component::JuceVST3Component(Steinberg::Vst::IHostApplication*) (this=0x5555559d2a20, h=0x0) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:2211
#7  0x00007ffff465d971 in juce::createComponentInstance(Steinberg::Vst::IHostApplication*) (host=0x0) at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:3694
#8  0x00007ffff46746a7 in juce::JucePluginFactory::createInstance(char const*, char const*, void**)
    (this=0x5555559d1150, cid=0x7fffffffc380 "\253\315\357\001\221\202\372\353OCTAPlDt\377\377\377\177Audio Module Class", sourceIid=0x555555998118 "\350\061\377\061\362\325C\001\222\216\273\356%ix\002", obj=0x7fffffffc308)
    at /home/kv/src/audio/PlugData/Libraries/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:3830
#9  0x00005555556f5102 in  ()
#10 0x0000555555703b29 in  ()
#11 0x0000555555700ca0 in  ()
#12 0x000055555567d099 in  ()
#13 0x000055555567de23 in  ()
#14 0x000055555567340a in  ()
#15 0x00005555555abc0f in  ()
#16 0x000055555559f3fa in  ()
#17 0x00007ffff7535630 in __libc_start_call_main (main=main@entry=0x55555559ecd0, argc=argc@entry=4, argv=argv@entry=0x7fffffffd738) at ../sysdeps/nptl/libc_start_call_main.h:58
#18 0x00007ffff75356f0 in __libc_start_main_impl (main=0x55555559ecd0, argc=4, argv=0x7fffffffd738, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd728) at ../csu/libc-start.c:392
#19 0x00005555555a3ec5 in  ()
```

**Comment by KottV** [comment]
It's a debug build. Release build does the same.

**Comment by timothyschoen** [comment]
Just noticed this, working on a fix right now!

**Comment by KottV** [comment]
Cool!

I found that it after 786b4dbc787ca6e16d6f51fec55077901a43f7b1

**Comment by timothyschoen** [comment]
Crazy, I just used clang-format there...

**Comment by KottV** [comment]
well, things're not so obvious, it crashes with older commits, but rarely

**Comment by timothyschoen** [comment]
Thanks for figuring that out, this looks like a pretty nasty bug...

**Comment by timothyschoen** [comment]
Might've fixed it, building now!

**Comment by timothyschoen** [comment]
Yup that fixed it! Very embarrassing bug, I should've paid more attention yesterday :(

**Comment by KottV** [comment]
yeah, no segfaults now! amazing
